# Generated by Django 5.2.17 on 2026-09-14 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.CharField(max_length=255)),
                ('trained_at', models.DateTimeField(auto_now=True)),
                ('n_samples', models.PositiveIntegerField(default=0)),
                ('cv_accuracy', models.FloatField(default=0.0)),
                ('feature_names', models.JSONField(default=list)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('features', models.JSONField()),
                ('label', models.BooleanField(null=True)),
                ('source', models.CharField(max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_samples', to='market_data.coin')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='signals.signal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
