# Generated by Django 5.2.17 on 2026-09-14 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('base_asset', models.CharField(max_length=10)),
                ('quote_asset', models.CharField(default='USDT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='PriceTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('change_percent_24h', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticker', to='market_data.coin')),
            ],
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=4)),
                ('open_time', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=24)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='market_data.coin')),
            ],
            options={
                'ordering': ['open_time'],
                'indexes': [models.Index(fields=['coin', 'timeframe', 'open_time'], name='market_data_coin_id_0d68b1_idx')],
                'unique_together': {('coin', 'timeframe', 'open_time')},
            },
        ),
    ]
