# Generated by Django 5.2.17 on 2026-09-14 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته\u200cشده')], default='open', max_length=10)),
                ('direction', models.CharField(max_length=5)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('result', models.CharField(blank=True, max_length=10)),
                ('pnl_percent', models.FloatField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_trades', to='market_data.coin')),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper_trade', to='signals.signal')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
