# Generated by Django 5.2.17 on 2026-09-14 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('BUY_STRONG', 'خرید قوی'), ('BUY_MEDIUM', 'خرید متوسط'), ('BUY_WEAK', 'خرید ضعیف'), ('WAIT', 'صبر'), ('SELL_WEAK', 'فروش ضعیف'), ('SELL_MEDIUM', 'فروش متوسط'), ('SELL_STRONG', 'فروش قوی')], max_length=12)),
                ('confidence', models.FloatField()),
                ('direction', models.CharField(max_length=4)),
                ('price', models.FloatField()),
                ('entry', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('risk_reward', models.FloatField()),
                ('holding_time_minutes', models.PositiveIntegerField()),
                ('risk_level', models.CharField(max_length=10)),
                ('explanation', models.JSONField(default=dict)),
                ('strategies', models.JSONField(default=list)),
                ('confidence_breakdown', models.JSONField(default=dict)),
                ('features', models.JSONField(default=dict)),
                ('ai_adjustment', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('open', 'باز'), ('tp', 'هدف (سود)'), ('sl', 'حد ضرر (زیان)'), ('expired', 'منقضی')], default='open', max_length=8)),
                ('result_pnl', models.FloatField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='market_data.coin')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
