# Generated by Django 5.2.17 on 2026-09-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='trend',
            field=models.CharField(blank=True, default='sideways', max_length=10),
        ),
    ]
