# Generated by Django 5.2.17 on 2026-09-15 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
        ('signals', '0002_signal_trend'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=30)),
                ('strategy_fa', models.CharField(blank=True, max_length=30)),
                ('total_predictions', models.PositiveIntegerField(default=0)),
                ('successful_predictions', models.PositiveIntegerField(default=0)),
                ('failed_predictions', models.PositiveIntegerField(default=0)),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_performances', to='market_data.coin')),
            ],
            options={
                'ordering': ['-accuracy_percentage'],
                'unique_together': {('coin', 'strategy_name')},
            },
        ),
    ]
