# Generated by Django 5.2.17 on 2026-09-14 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('info', 'اطلاع'), ('success', 'موفق'), ('warning', 'هشدار'), ('error', 'خطا')], default='info', max_length=10)),
                ('sound', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_data.coin')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
